dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install pytest-cov codecov eve
services:
  - mongodb  # this might not launch fast enough - we could need a delay
script:
  - python -m pytest --cov=./pypersist
after_success:
  - codecov
